### ISSUE TITLE
Object not found

### ISSUE THREAD

**Issue by KOmolowo** [alphabit-technology/erpnext-restaurant#28]
After installation, I could not see were to create table and production. The error message on Object click is  "Object not found".

Erpnext V13.14 OVA production

**Comment by quantumbitcore** [comment]
You have installed frappe_helper app?

**Comment by KOmolowo** [comment]
Yes, I have. Does it matter the order of installation?

**Comment by quantumbitcore** [comment]
You need to run bench migrate and bench build, if you are in production mode also bench restart.

**Comment by KOmolowo** [comment]
Done all these, but the same issue. If I click on the object, it returns 'Page Restaurant-Object Not Found'

**Comment by KOmolowo** [comment]
I also have this error while installing Frappe-Helper:
('Module Def' 'Frappe Helper', IntegrityError (1062, "Duplicate entry 'Frappe Helper' for key 'PRIMARY' "))

**Comment by quantumbitcore** [comment]
Do you have installed in public server? I can help you.

**Comment by KOmolowo** [comment]
Unfortunately it's privately hosted.

I think the issue may be to get rid completely of frappe_helper from
site1.local, then reinstall afresh.

I can do the settings, but click on Restaurant opens blank, so cannot
create the rooms and tables. Then if you click Object, it returns
Restaurant Object Not found

**Comment by quantumbitcore** [comment]
Please try uninstall both apps, execute bench migrate, and reinstall.

**Comment by KOmolowo** [comment]
Thank you for your good work. Good programming on the Restaurant app. I
have uninstalled both apps. It's installed now. I can configure Rooms, and
Tables. But the error, 'Restaurant Object not Found' is still showing if I
click on the Object.

Then, when you pick a table and make entries, you need to refresh and enter
the Table number again to see the entry. It's not good enough for end
users. What can be done to minimise frequent refreshing?

Is there any guide on how to use the app? How to send to Production, change
status, view status, etc.

Then in a Table, you can have multiple orders. We want all the orders on
that table to come as one bill instead of multiple bills to print.

What if a cashier, not the Waiter is enabled to collect payment?

Will surely appreciate your help on this, please.

**Comment by quantumbitcore** [comment]
For the error "Restaurant Object Object not found" I would like to see some
screen print or the browser console, to solve the problem of refreshing the
screen, you must configure your server (not frappe) in production mode, for
multiple orders you can change the  option in restaurant settings (allow
multiple orders)
