### ISSUE TITLE
Page restaurant-object not found

### ISSUE THREAD

**Issue by Hafnianusha** [alphabit-technology/erpnext-restaurant#29]
Hi , after installation , in restaurant management module when i going to Restaurant its showing a blank page , also while clicking in object "Page restaurant-object not found" is popping up

**Comment by Hafnianusha** [comment]
showing bank page is fixed now . But "Page restaurant-object not found" is still there . i think due to this issue ,  can't execute 'production unit' working flow

**Comment by josephvct** [comment]
> showing bank page is fixed now . But "Page restaurant-object not found" is still there . i think due to this issue , can't execute 'production unit' working flow

Hi, How are you fix for blank screen? I got same problem.

Thanks.

**Comment by SajadAlimoradi** [comment]
Hello, if you search for "Domain settings," you will find a list. By checking the restaurant option, you can resolve your problem.
