### ISSUE TITLE
Restaurant Management app Lags and Need to Refresh everytime

### ISSUE THREAD

**Issue by OsiFTG** [alphabit-technology/erpnext-restaurant#44]
Hi quantumbitcore.

first of all. i love what you did for the restaurant management. i have integrate it to ERPNext and test it out. the UI is good and the functions are even better. its just that, there are lags on the restaurant management app. each time i add new tables, add new item to the menu and add item to the cart, it lags and didn't update directly. i have to refresh the website first to see the changes in the UI. maybe you could support me with some insights on how to mitigate this lag? i am using ERPNext V13 btw.

i suspect it has something to do with ERPNext Socket.io that handles the real-time updates, but i am not sure also. my VM has adequate numbers of cores and RAM so the server side will not be the issue.  i am still new with this ERPNext hahahaha. Please do assist me on solving this thank you so much.

**Comment by quantumbitcore** [comment]
Yes Sr, your problem is soketio, you need set your server in production (server) not frappe.

**Comment by OsiFTG** [comment]
Hi quantumbitcore

i believe i already run my ERPNext in production mode but the restaurant app still lags. maybe can help me out? like for example, how to check if my ERPNext is running and the socket.io is working as well.

Thank you

**Comment by OsiFTG** [comment]
Hello.

i Finally manage to run it without lag anymore, the production mode really does working, just the socket.io and redis causing issue previously. Thank you for your help now is fixed. 

but i notice something, when you add a new pricing rule for promotion (example, buy 1 food free 1 drink), the drink didn't appear in the POS menu, but it appears in the invoice. is it suppose to be like that? i believe this caused an issue because the free drink didn't go to the drink kitchen to make the order.

**Comment by OsiFTG** [comment]
Hi, so i finally manage to run it perfectly using nginx and supervisor. your app is great. just wondering, can your restaurant management app run if i am using APACHE HTTPD instead of Nginx??

Thank you in advance

**Comment by quantumbitcore** [comment]
That is exactly what you needed to run your server in production mode, about running it in apache I'm not sure, that would be a question for frappe to know in which server environments the framework can run.

**Comment by OsiFTG** [comment]
how does your application work with the socket.io real time actually? maybe from that perspective then i can try to add the configuration to my apache

Thank you in advance

**Comment by alphabit-technology** [comment]
I use frappe.realtime, if you can run frappe on apache is possible that socketio work too.

**Comment by sinhpn92** [comment]
Hello,
I have the same issue. I setup to run the erpnext by following this guide: https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

How can to fix by docker? sudo is not found on docker container when using bash.

Thank you.

**Comment by alphabit-technology** [comment]
I have not been able to complete a version in frappe docker.
