### ISSUE TITLE
Does restaurant management app able to do online order in ERPNext

### ISSUE THREAD

**Issue by barbq87** [alphabit-technology/erpnext-restaurant#45]
I would like to ask whether this restaurant management app able to connect with the E-Commerce module in ERPNext to make online ordering?

**Comment by quantumbitcore** [comment]
No sr.

**Comment by barbq87** [comment]
If that is the case, does it possible to connect with the E Commerce in ERPNext. For instance, customer make order through the E Commerce platform and then the order will send to the restaurant management app to produce the order.
